# Exercise 9

## Mashable news stories analysis

Predicting if a news story is going to be popular


In [1]:
import pandas as pd
import numpy as np

url = 'https://raw.githubusercontent.com/albahnsen/PracticalMachineLearningClass/master/datasets/mashable.csv'
train_df = pd.read_csv(url, index_col=0)
train_df.head()

url  timedelta  \
0  http://mashable.com/2014/12/10/cia-torture-rep...       28.0   
1  http://mashable.com/2013/10/18/bitlock-kicksta...      447.0   
2  http://mashable.com/2013/07/24/google-glass-po...      533.0   
3  http://mashable.com/2013/11/21/these-are-the-m...      413.0   
4  http://mashable.com/2014/02/11/parking-ticket-...      331.0   

   n_tokens_title  n_tokens_content  n_unique_tokens  n_non_stop_words  \
0             9.0             188.0         0.732620               1.0   
1             7.0             297.0         0.653199               1.0   
2            11.0             181.0         0.660377               1.0   
3            12.0             781.0         0.497409               1.0   
4             8.0             177.0         0.685714               1.0   

   n_non_stop_unique_tokens  num_hrefs  num_self_hrefs  num_imgs   ...     \
0                  0.844262        5.0             1.0       1.0   ...      
1                  0.815789        9.0             4.0       1.0   ...      
2                  0.775701        4.0             3.0       1.0   ...      
3                  0.677350       10.0             3.0       1.0   ...      
4                  0.830357        3.0             2.0       1.0   ...      

   min_positive_polarity  max_positive_polarity  avg_negative_polarity  \
0               0.200000                   0.80              -0.487500   
1               0.160000                   0.50              -0.135340   
2               0.136364                   1.00               0.000000   
3               0.100000                   1.00              -0.195701   
4               0.100000                   0.55              -0.175000   

   min_negative_polarity  max_negative_polarity  title_subjectivity  \
0                  -0.60              -0.250000                 0.9   
1                  -0.40              -0.050000                 0.1   
2                   0.00               0.000000                 0.3   
3                  -0.40              -0.071429                 0.0   
4                  -0.25              -0.100000                 0.0   

   title_sentiment_polarity  abs_title_subjectivity  \
0                       0.8                     0.4   
1                      -0.1                     0.4   
2                       1.0                     0.2   
3                       0.0                     0.5   
4                       0.0                     0.5   

   abs_title_sentiment_polarity  Popular  
0                           0.8        1  
1                           0.1        0  
2                           1.0        0  
3                           0.0        0  
4                           0.0        0  

[5 rows x 61 columns]

In [2]:
train_df.shape

(6000, 61)

In [3]:
X = train_df.drop(['url', 'Popular'], axis=1)
y = train_df['Popular']

In [4]:
y.mean()

0.5

In [5]:
# train/test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Exercise 9.1

Estimate a Decision Tree Classifier and a Logistic Regresion

Evaluate using the following metrics:
* Accuracy
* F1-Score

In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
clf = DecisionTreeClassifier(random_state=1)
clf.fit(X_train, y_train)
yclf_pred = clf.predict(X_test)
print(metrics.classification_report(y_test,yclf_pred))

             precision    recall  f1-score   support

          0       0.54      0.55      0.55       744
          1       0.55      0.53      0.54       756

avg / total       0.54      0.54      0.54      1500



In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
logreg= LogisticRegression()
logreg.fit(X_train, y_train)
ylog_pred = logreg.predict(X_test)
print(metrics.classification_report(y_test,ylog_pred))

             precision    recall  f1-score   support

          0       0.61      0.68      0.64       744
          1       0.65      0.58      0.61       756

avg / total       0.63      0.63      0.63      1500



# Exercise 9.2

Estimate 300 bagged samples

Estimate the following set of classifiers:

* 100 Decision Trees where max_depth=None
* 100 Decision Trees where max_depth=2
* 100 Logistic Regressions

In [8]:
# crear 100 "bolsas" con semilla 155
np.random.seed(155)
n_samples = X.shape[0]
n_B = 100
samples = [np.random.choice(a=n_samples, size=n_samples, replace=True) for _ in range(1, n_B +1 )]
samples

[array([4473, 5886,  151, ..., 4184, 2316, 3933]),
 array([1314, 2618, 5712, ..., 4963, 1751, 5907]),
 array([2567, 3746, 4551, ..., 4186, 4520, 4306]),
 array([1895,  588, 2354, ..., 2165, 4305, 1532]),
 array([  33,  298, 5427, ..., 4578, 2585, 4049]),
 array([5955,  971,  866, ..., 5614, 1868, 4457]),
 array([3635, 2790, 3529, ..., 3833,  630, 5664]),
 array([ 143, 5077, 3090, ..., 3307, 3395, 2730]),
 array([4648, 2263,  153, ..., 4636, 5020,  358]),
 array([5838, 3429, 1186, ..., 5131, 1673, 1535]),
 array([4748, 2448, 2634, ...,  887, 1714, 5490]),
 array([2348,  178, 1652, ...,  395,  699, 4288]),
 array([2658, 5509, 1723, ..., 5923, 3552, 4059]),
 array([1952, 5175, 3682, ..., 4760, 4202,  461]),
 array([3347,  835, 1153, ..., 4695, 5395, 2149]),
 array([ 421, 3793, 5312, ...,  474, 3552, 5283]),
 array([4315, 5703, 4703, ..., 2676, 1517, 1074]),
 array([3805, 4256, 5986, ...,  231, 3530, 4934]),
 array([4078, 2154, 5746, ...,  290,  534,  788]),
 array([1429, 4489, 1786, ..., 

In [9]:
# crear 100 "bolsas" con semilla 125
np.random.seed(125)
n_samples = X.shape[0]
n_B = 100
samples2 = [np.random.choice(a=n_samples, size=n_samples, replace=True) for _ in range(1, n_B +1 )]
# crear 100 "bolsas" con semilla 123
np.random.seed(123)
n_samples = X.shape[0]
n_B = 100
samples3 = [np.random.choice(a=n_samples, size=n_samples, replace=True) for _ in range(1, n_B +1 )]

In [10]:
models = {'log': LogisticRegression(solver='liblinear',C=1e9, random_state=155),
          'dt1': DecisionTreeClassifier(max_depth=None, random_state=125),
          'dt2': DecisionTreeClassifier(max_depth=2, random_state=123)}

In [11]:
y_pred = pd.DataFrame (columns =models.keys(),index= y_test.index )

In [12]:
#for tp in models.keys():
from sklearn.ensemble import BaggingClassifier
for i, model  in models.items():
    bagreg = BaggingClassifier(model, n_estimators=100,bootstrap=True, oob_score=True,n_jobs=-1)
    bagreg.fit(X_train, y_train)
    y_pred[i] = bagreg.predict(X_test)
y_pred.head()

log  dt1  dt2
1483    1    1    1
2185    1    1    1
2520    1    1    1
3721    1    1    1
3727    0    0    0

# Exercise 9.3

Ensemble using majority voting

Evaluate using the following metrics:
* Accuracy
* F1-Score

In [15]:
from sklearn.ensemble import VotingClassifier
alg1 = LogisticRegression(solver='liblinear',C=1e9, random_state=155)
alg2 = DecisionTreeClassifier(max_depth=None, random_state=125)
alg3 = DecisionTreeClassifier(max_depth=2, random_state=123)

bagreg1 = BaggingClassifier(alg1, n_estimators=100,bootstrap=True, oob_score=True,n_jobs=-1)
bagreg2 = BaggingClassifier(alg2, n_estimators=100,bootstrap=True, oob_score=True,n_jobs=-1)
bagreg3 = BaggingClassifier(alg3, n_estimators=100,bootstrap=True, oob_score=True,n_jobs=-1)

Alg = VotingClassifier(estimators=[('LR',bagreg1),('DT',bagreg2),('DT2',bagreg3)], voting='hard')
Alg.fit(X_train,y_train)

VotingClassifier(estimators=[('LR', BaggingClassifier(base_estimator=LogisticRegression(C=1000000000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=155,
          solver='liblinear', tol=0.0001, verb...stimators=100, n_jobs=-1, oob_score=True,
         random_state=None, verbose=0, warm_start=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [16]:
y_predMV = Alg.predict(X_test)
print(metrics.classification_report(y_test,y_predMV))

             precision    recall  f1-score   support

          0       0.64      0.66      0.65       744
          1       0.65      0.63      0.64       756

avg / total       0.65      0.65      0.65      1500



C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


# Exercise 9.4

Estimate te probability as %models that predict positive

Modify the probability threshold and select the one that maximizes the F1-Score

In [41]:
#Estimate the probability as %models that predict positive

test = pd.DataFrame(y_predMV, columns=['g'])
popular = pd.crosstab(test.g, columns = 'count')
popular/popular.sum()

col_0  count
g           
0      0.514
1      0.486

In [18]:
prob=np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
thre_prob1=pd.DataFrame(index=y_test.index, columns=prob)
for i in prob:
    bagreg1.fit(X_train, y_train)
    thre_prob1[i] = (bagreg1.predict_proba(X_test)>= i).astype(np.int)

In [19]:
prob=np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
thre_prob2=pd.DataFrame(index=y_test.index, columns=prob)
for i in prob:
    bagreg2.fit(X_train, y_train)
    thre_prob2[i] = (bagreg2.predict_proba(X_test)>= i).astype(np.int)

In [20]:
prob=np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
thre_prob3=pd.DataFrame(index=y_test.index, columns=prob)
for i in prob:
    bagreg3.fit(X_train, y_train)
    thre_prob3[i] = (bagreg3.predict_proba(X_test)>= i).astype(np.int)

In [21]:
f1bagreg1=pd.DataFrame(index=thre_prob1.columns, columns=['F1_score'])
for c in thre_prob1.columns:
    f1bagreg1.loc[c]=[metrics.f1_score(thre_prob1[c], y_test)]
f1bagreg1

C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true samples.
  'recall', 'true', average, warn_for)


F1_score
0.1    0.667557
0.2    0.649115
0.3    0.596357
0.4    0.509363
0.5    0.404337
0.6    0.214286
0.7   0.0631579
0.8  0.00264201
0.9           0

In [22]:
f1bagreg2=pd.DataFrame(index=thre_prob2.columns, columns=['F1_score'])
for c in thre_prob2.columns:
    f1bagreg2.loc[c]=[metrics.f1_score(thre_prob2[c], y_test)]
f1bagreg2

F1_score
0.1    0.668739
0.2    0.651543
0.3    0.592412
0.4    0.489209
0.5    0.355116
0.6    0.218212
0.7      0.1002
0.8   0.0422535
0.9  0.00774194

In [23]:
f1bagreg3=pd.DataFrame(index=thre_prob3.columns, columns=['F1_score'])
for c in thre_prob3.columns:
    f1bagreg3.loc[c]=[metrics.f1_score(thre_prob3[c], y_test)]
f1bagreg3

C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true samples.
  'recall', 'true', average, warn_for)


F1_score
0.1  0.670213
0.2  0.670213
0.3  0.622659
0.4  0.466895
0.5  0.361478
0.6  0.237947
0.7         0
0.8         0
0.9         0

# Exercise 9.5

Ensemble using weighted voting using the oob_error

Evaluate using the following metrics:
* Accuracy
* F1-Score

In [46]:
alg1 = LogisticRegression(solver='liblinear',C=1e9, random_state=155)
alg2 = DecisionTreeClassifier(max_depth=None, random_state=125)
alg3 = DecisionTreeClassifier(max_depth=2, random_state=123)

bagreg1 = BaggingClassifier(alg1, n_estimators=100,bootstrap=True, oob_score=True,n_jobs=-1)
bagreg2 = BaggingClassifier(alg2, n_estimators=100,bootstrap=True, oob_score=True,n_jobs=-1)
bagreg3 = BaggingClassifier(alg3, n_estimators=100,bootstrap=True, oob_score=True,n_jobs=-1)

In [47]:
bagreg1.fit(X_train, y_train)
bagreg2.fit(X_train, y_train)
bagreg3.fit(X_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=123,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=100, n_jobs=-1, oob_score=True,
         random_state=None, verbose=0, warm_start=False)

In [49]:
errors = np.zeros(bagreg1.n_estimators)
y_pred_all_ = np.zeros((X_test.shape[0], bagreg1.n_estimators))

for i in range(bagreg1.n_estimators):
    oob_sample = ~bagreg1.estimators_samples_[i]
    y_pred_ = bagreg1.estimators_[i].predict(X_train.values[oob_sample])
    errors[i] = metrics.accuracy_score(y_pred_, y_train.values[oob_sample])
    y_pred_all_[:, i] = bagreg1.estimators_[i].predict(X_test)
    
alpha1 = (1 - errors) / (1 - errors).sum()
bag1 = pd.DataFrame((np.sum(y_pred_all_ * alpha1, axis=1) >= 0.5).astype(np.int),columns=['bag1'])
bag11 = pd.DataFrame(np.sum(y_pred_all_ * alpha1, axis=1),columns=['bag1'])

In [55]:
alpha1 

array([0.00985497, 0.01002783, 0.01019246, 0.0098157 , 0.00983244,
       0.00993058, 0.00969761, 0.00972838, 0.00982538, 0.00966098,
       0.01054111, 0.00999443, 0.01033274, 0.01038099, 0.00985744,
       0.00982016, 0.01035932, 0.01020458, 0.00991363, 0.01018015,
       0.01025561, 0.0100489 , 0.01004588, 0.00990435, 0.00998854,
       0.00972345, 0.0098371 , 0.0099745 , 0.01020136, 0.01019927,
       0.01039967, 0.01013254, 0.00962127, 0.00994277, 0.01005275,
       0.00981987, 0.01012352, 0.01019662, 0.01004495, 0.00995595,
       0.01037836, 0.01013099, 0.00974324, 0.01012171, 0.00976229,
       0.00991219, 0.01009332, 0.0093019 , 0.0096611 , 0.01038209,
       0.01020214, 0.01036386, 0.0099236 , 0.0096887 , 0.00991537,
       0.00990546, 0.00996049, 0.00982538, 0.01000884, 0.00941614,
       0.01002631, 0.01020485, 0.01029304, 0.01006422, 0.00984131,
       0.01047104, 0.01039642, 0.00983288, 0.00968577, 0.00968437,
       0.00955545, 0.01014865, 0.01024721, 0.00992741, 0.00979

In [50]:
errors = np.zeros(bagreg2.n_estimators)
y_pred_all_ = np.zeros((X_test.shape[0], bagreg2.n_estimators))

for i in range(bagreg2.n_estimators):
    oob_sample = ~bagreg2.estimators_samples_[i]
    y_pred_ = bagreg2.estimators_[i].predict(X_train.values[oob_sample])
    errors[i] = metrics.accuracy_score(y_pred_, y_train.values[oob_sample])
    y_pred_all_[:, i] = bagreg2.estimators_[i].predict(X_test)
    
alpha2 = (1 - errors) / (1 - errors).sum()
bag2 = pd.DataFrame((np.sum(y_pred_all_ * alpha2, axis=1) >= 0.5).astype(np.int),columns=['bag2'])
bag22 = pd.DataFrame(np.sum(y_pred_all_ * alpha2, axis=1),columns=['bag2'])

In [54]:
alpha2

array([0.00986697, 0.00998912, 0.0098804 , 0.00986859, 0.00983171,
       0.01045415, 0.00999384, 0.00986352, 0.010221  , 0.01040307,
       0.010142  , 0.01026833, 0.01053522, 0.01002231, 0.01032548,
       0.00958659, 0.01021472, 0.0095641 , 0.00954052, 0.00995843,
       0.01029069, 0.00983346, 0.00974854, 0.00993953, 0.00987946,
       0.01022183, 0.01018201, 0.01024611, 0.00956691, 0.01000424,
       0.010096  , 0.01007824, 0.00991073, 0.00996056, 0.01011556,
       0.01001934, 0.01012825, 0.00953646, 0.01027396, 0.01001936,
       0.01047096, 0.00986419, 0.00994478, 0.01031278, 0.01009644,
       0.00999618, 0.00983023, 0.00974486, 0.0097467 , 0.01055184,
       0.00936146, 0.01013512, 0.01021636, 0.00994076, 0.00994871,
       0.00985999, 0.00987669, 0.01001783, 0.01024611, 0.00943667,
       0.01003931, 0.00955466, 0.01008607, 0.0102178 , 0.00979708,
       0.0097309 , 0.00995529, 0.01006422, 0.0095266 , 0.0101933 ,
       0.00980765, 0.00995311, 0.0096162 , 0.01020323, 0.01019

In [51]:
errors = np.zeros(bagreg3.n_estimators)
y_pred_all_ = np.zeros((X_test.shape[0], bagreg3.n_estimators))

for i in range(bagreg3.n_estimators):
    oob_sample = ~bagreg3.estimators_samples_[i]
    y_pred_ = bagreg3.estimators_[i].predict(X_train.values[oob_sample])
    errors[i] = metrics.accuracy_score(y_pred_, y_train.values[oob_sample])
    y_pred_all_[:, i] = bagreg3.estimators_[i].predict(X_test)
    
alpha3 = (1 - errors) / (1 - errors).sum()
bag3 = pd.DataFrame((np.sum(y_pred_all_ * alpha3, axis=1) >= 0.5).astype(np.int),columns=['bag3'])
bag33 = pd.DataFrame(np.sum(y_pred_all_ * alpha3, axis=1),columns=['bag3'])

In [56]:
alpha3

array([0.00956002, 0.01020353, 0.01009158, 0.01011911, 0.01059973,
       0.01019102, 0.01030535, 0.01033949, 0.01029704, 0.00993985,
       0.00995963, 0.01013416, 0.00971391, 0.00960546, 0.01004612,
       0.01004965, 0.01067843, 0.00991464, 0.01008715, 0.01051938,
       0.01057838, 0.01006094, 0.00984156, 0.0098218 , 0.01016118,
       0.0098695 , 0.00993917, 0.00979103, 0.01012203, 0.00990865,
       0.01016355, 0.01015267, 0.00983358, 0.01012585, 0.00972218,
       0.01001487, 0.01043371, 0.00988924, 0.00932953, 0.01029074,
       0.00987133, 0.01006783, 0.01015789, 0.00978428, 0.00989185,
       0.01018075, 0.01024687, 0.00997381, 0.00967716, 0.00973275,
       0.01010021, 0.00997366, 0.00988244, 0.01011102, 0.01022572,
       0.00977668, 0.01077102, 0.00948377, 0.00935973, 0.00965969,
       0.00989523, 0.00956196, 0.01000766, 0.01033063, 0.00957923,
       0.01009641, 0.01005656, 0.01026497, 0.01046763, 0.00973187,
       0.00981898, 0.00958636, 0.01035828, 0.00963379, 0.00979

In [58]:
Yresul = pd.concat([bag1, bag2,bag3], axis=1, sort=False)
Yresul.head(10)

bag1  bag2  bag3
0     1     1     1
1     1     1     1
2     1     1     1
3     1     1     1
4     0     0     0
5     0     1     1
6     0     0     0
7     0     0     0
8     1     1     0
9     1     0     1

# Exercise 9.6

Estimate te probability of the weighted voting

Modify the probability threshold and select the one that maximizes the F1-Score

In [60]:
Yest = np.round(Yresul.mean(axis=1)).astype(int)
popular = pd.crosstab(Yest, columns = 'count')
popular/popular.sum()

col_0     count
row_0          
0      0.516667
1      0.483333

In [28]:
prob=np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
thre_prob=pd.DataFrame(index=y_test.index, columns=prob)
for i in prob:
    thre_prob[i] = (Alg2.predict_proba(X_test)>= i).astype(np.int)

In [29]:
thre_prob.head()

0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9
1483    1    1    0    0    0    0    0    0    0
2185    1    1    1    0    0    0    0    0    0
2520    1    1    1    0    0    0    0    0    0
3721    1    1    1    0    0    0    0    0    0
3727    1    1    1    1    1    1    0    0    0

In [30]:
f1WV=pd.DataFrame(index=thre_prob.columns, columns=['F1_score'])
for c in thre_prob.columns:
    f1WV.loc[c]=[metrics.f1_score(thre_prob[c], y_test)]

C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true samples.
  'recall', 'true', average, warn_for)


In [31]:
f1WV

F1_score
0.1   0.670213
0.2   0.666072
0.3   0.612032
0.4   0.489083
0.5   0.370852
0.6   0.199662
0.7  0.0390356
0.8          0
0.9          0

# Exercise 9.7

Estimate a logistic regression using as input the estimated classifiers

Modify the probability threshold such that maximizes the F1-Score

In [62]:
z=(bagreg1.n_estimators)
y_pred_all1 = np.zeros((X_test.shape[0], z))
X_train_1 = np.zeros((X_train.shape[0], z))
for i in range(z):
    X_train_1[:, i] = bagreg1.estimators_[i].predict(X_train)
    y_pred_all1[:, i] = bagreg1.estimators_[i].predict(X_test)
X_train_1 = pd.DataFrame(X_train_1)
y_pred_all1 = pd.DataFrame(y_pred_all1)

z=(bagreg2.n_estimators)
y_pred_all2 = np.zeros((X_test.shape[0], z))
X_train_2 = np.zeros((X_train.shape[0], z))
for i in range(z):
    X_train_2[:, i] = bagreg2.estimators_[i].predict(X_train)
    y_pred_all2[:, i] = bagreg2.estimators_[i].predict(X_test)
X_train_2 =pd.DataFrame(X_train_2)
y_pred_all2 = pd.DataFrame(y_pred_all2)

z=(bagreg3.n_estimators)
y_pred_all3 = np.zeros((X_test.shape[0], z))
X_train_3 = np.zeros((X_train.shape[0], z))
for i in range(z):
    X_train_3[:, i] = bagreg3.estimators_[i].predict(X_train)
    y_pred_all3[:, i] = bagreg3.estimators_[i].predict(X_test)
X_train_3=pd.DataFrame(X_train_3)
y_pred_all3 = pd.DataFrame(y_pred_all3)

In [63]:
X_train_all = pd.concat([X_train_1, X_train_2, X_train_3], axis=1, sort=False)
X_train_all.head()

0    1    2    3    4    5    6    7    8    9  ...    90   91   92   93  \
0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0 ...   1.0  1.0  1.0  1.0   
1  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0 ...   1.0  1.0  1.0  1.0   
2  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0 ...   0.0  1.0  0.0  0.0   
3  1.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0 ...   1.0  1.0  1.0  1.0   
4  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0 ...   1.0  1.0  1.0  1.0   

    94   95   96   97   98   99  
0  1.0  1.0  1.0  1.0  1.0  1.0  
1  1.0  1.0  1.0  1.0  1.0  1.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  1.0  1.0  1.0  0.0  1.0  1.0  
4  1.0  1.0  1.0  1.0  1.0  1.0  

[5 rows x 300 columns]

In [64]:
y_train_total = pd.concat([y_pred_all1, y_pred_all2, y_pred_all3], axis=1, sort=False)
y_train_total.head()

0    1    2    3    4    5    6    7    8    9  ...    90   91   92   93  \
0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0 ...   1.0  1.0  1.0  1.0   
1  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0 ...   1.0  1.0  1.0  1.0   
2  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0 ...   1.0  1.0  1.0  1.0   
3  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0 ...   1.0  1.0  1.0  1.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   

    94   95   96   97   98   99  
0  1.0  1.0  1.0  1.0  1.0  1.0  
1  1.0  1.0  1.0  1.0  1.0  1.0  
2  1.0  1.0  1.0  1.0  1.0  1.0  
3  1.0  1.0  1.0  1.0  1.0  1.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 300 columns]

In [65]:
from sklearn.linear_model import LogisticRegressionCV
lr = LogisticRegressionCV(cv=5)
lr.fit(X_train_all, y_train)

y_predt = lr.predict(y_train_total)
metrics.f1_score(y_predt, y_test), metrics.accuracy_score(y_predt, y_test)

(0.652980132450331, 0.6506666666666666)